prefix midi: <http://purl.org/midi-ld/midi#>
prefix midi-note: <http://purl.org/midi-ld/notes/>
prefix midi-prog: <http://purl.org/midi-ld/programs/>
prefix prov: <http://www.w3.org/ns/prov#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT
	DISTINCT ?event
FROM <http://purl.org/midi-ld/piece/2eb43ce7edf27b505bcc0dfb6c283784>
WHERE {
   [] a midi:Track ;
        midi:hasEvents ?events .
   ?events rdf:rest*/rdf:first ?event .
	 BIND (xsd:integer(SUBSTR(str(?event), 77)) AS ?id)
} ORDER BY ?id
LIMIT 100
OFFSET 850
